### Simultaneous multivariate polynomial equations solution ###

When a two layer fluid flows over topography, there exist a number
of different solutions depending on the relative size of the flow
speed and the wave speed.

These are termed 'critical', 'subcritical' and 'supercritical' (the
latter two I term here as 'extracritical').

The following equations define the bounding lines between critical
and extra critical behaviour:

\\[ U_0^2 \left(\frac{d_0^2}{d_{1c}^3} + \frac{(1 - d_0)^2}{(1 - d_{1c} - h)^3} \right) - 1 = 0 \\]

\\[ 0.5 U_0^2 \left( \frac{d_0^2}{d_{1c}^2} - \frac{(1 - d_0)^2}{(1 - d_{1c} - h)^2} \right) + d_{1c} + (h - d_0) = 0 \\]

[eq1]: http://latex.codecogs.com/gif.latex?U_0%5E2%20%5Cleft%28%5Cfrac%7Bd_0%5E2%7D%7Bd_%7B1c%7D%5E3%7D%20&plus;%20%5Cfrac%7B%281%20-%20d_0%29%5E2%7D%7B%281%20-%20d_%7B1c%7D%20-%20h%29%5E3%7D%20%5Cright%29%20-%201%20%3D%200
[eq2]: http://latex.codecogs.com/gif.latex?%5Cfrac%7B1%7D%7B2%7D%20U_0%5E2%20%5Cleft%28%20%5Cfrac%7Bd_0%5E2%7D%7Bd_%7B1c%7D%5E2%7D%20-%20%5Cfrac%7B%281%20-%20d_0%29%5E2%7D%7B%281%20-%20d_%7B1c%7D%20-%20h%29%5E2%7D%20%5Cright%29%20&plus;%20d_%7B1c%7D%20&plus;%20%28h%20-%20d_0%29%20%3D%200

I want to eliminate \\(d_{1c}\\) and find solutions to these
equations in \\((h, U_0)\\).

Simplifying factors:

- I only need answers for *given* \\(d_0\\)
- *I do not need exact solutions*, just an outline of the solution
  curves, so this can be solved either analytically or numerically.
- I only want to plot over the region (h, U0) = (0,0) to (0.5, 1).

I'd like to solve this using modules available in the Enthought
distribuion (numpy, scipy, sympy), but really don't know where to
start. It's the elimination of the variable d1c that really confuses
me.  

Here are the equations in python:

    :::python
    def eq1(h, U0, d1c, d0=0.1):
        f = (U0) ** 2 * ((d0 ** 2 / d1c ** 3) + (1 - d0) ** 2 / (1 - d1c - h) ** 3) - 1
        return f

    def eq2(h, U0, d1c, d0=0.1):
        f = 0.5 * (U0) ** 2 * ((d0 ** 2 / d1c ** 2) - (1 - d0) ** 2 / (1 - d1c - h) ** 2) + d1c + (h - d0)
        return f

I'm expecting a solution that has a number of solution branches (not
always physical, but don't worry about that) and looks roughly
like this:




